// components/experience.vue
<script setup lang="ts">
interface ExperienceProps {
	title: string;
	subtitle: string;
	location: string;
	date: string;
}
defineProps<ExperienceProps>();
</script>

<template>
	<div class="flex-grow">
		<h3 class="font-semibold">{{ title }}</h3>
		<h4>{{ subtitle }}</h4>
		<p class="text-sky-800">{{ date }}</p>
		<p class="text-sky-800">{{ location }}</p>
	</div>
</template>

// src/lib/components/experience.svelte
<script lang="ts">
	import type { Experience } from '../experience';

	export let experience: Experience;
</script>

<div class="space-y-3">
	<div>
		<h3 class="font-semibold">{experience.title}</h3>
		<h4>{experience.employer}</h4>
		<p class="text-sky-800">{experience.duration}</p>
		<p class="text-sky-800">{experience.location}</p>
	</div>
</div>
